// 지식/*.md 를 읽어 템플릿.html 에 내장하고 ../챗봇_시안.html 을 만든다. (node 빌드.js)
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.join(__dirname,'..'), kdir=path.join(root,'지식');
const files=fs.readdirSync(kdir).filter(f=>/^\d\d_.*\.md$/.test(f)).sort();
const kb=[];
for(const f of files){
  const txt=fs.readFileSync(path.join(kdir,f),'utf8');
  txt.split(/\n(?=## )/).slice(1).forEach(sec=>{
    const lines=sec.split('\n'); const title=lines[0].replace(/^## /,'').trim();
    let status='',kw=[],body=[];
    lines.slice(1).forEach(l=>{
      if(l.startsWith('- 상태:'))status=l.slice(5).trim();
      else if(l.startsWith('- 키워드:'))kw=l.slice(6).split(',').map(s=>s.trim()).filter(Boolean);
      else body.push(l);
    });
    kb.push({file:f.replace(/\.md$/,''),title,status,kw,body:body.join('\n').trim()});
  });
}
const tpl=fs.readFileSync(path.join(__dirname,'템플릿.html'),'utf8');
const wines=JSON.parse(fs.readFileSync(path.join(__dirname,'와인_추천_데이터.json'),'utf8'));
const menuSource=JSON.parse(fs.readFileSync(path.join(__dirname,'메뉴판_허용자료_1008.json'),'utf8'));
const foods=menuSource.rows.filter(r=>/^MENU\s+\d+/.test(r.values[0])&&r.values[2]).map(r=>({name:r.values[2],description:r.description||'',sourceRow:r.row}));
const wineMenu=menuSource.rows.filter(r=>/wine/i.test(r.values[0]||'')&&r.values[2]).map(r=>({category:String(r.values[0]).replace(/\s+\d+.*$/,'').trim(),name:r.values[2],english:r.values[4],origin:r.values[5],variety:r.values[6]}));
const safe=s=>JSON.stringify(s).replace(/</g,'\\u003c');
const sourceHash=crypto.createHash('sha256').update(JSON.stringify(kb)+JSON.stringify(wines)+JSON.stringify(foods)+JSON.stringify(wineMenu)+tpl).digest('hex').slice(0,10);
const endpoint=process.env.HARAGO_AI_ENDPOINT||'';
if(endpoint&&!/^https:\/\/[a-z0-9-]+\.[a-z0-9-]+\.workers\.dev\/api\/chat$/.test(endpoint))throw new Error('AI endpoint must be an HTTPS Cloudflare Worker URL.');
const logEnabled=process.env.HARAGO_QUESTION_LOG_ENABLED==='true';
// The server accepts only the same canonical checklist items shown on the page.
function checklistTasks(body){
  let group='기본 준비';
  return String(body).split('\n').filter(line=>line.trim()).map(line=>{
    let s=line.trim(),task=/^-\s/.test(s);s=s.replace(/^-\s*/,'');
    if(/홀 준비 후|주간 업무는/.test(s)){group=/주간/.test(s)?'주간 업무 · 해당 요일만':'홀 준비 후 · 18:30';return {task:false};}
    const colon=s.indexOf(':');
    if(task&&colon>0&&/시|퇴근 전/.test(s.slice(0,colon)))return {group:s.slice(0,colon),text:s.slice(colon+1).trim(),task:true};
    return {group,text:s,task};
  }).filter(e=>e.task).map(({group,text})=>({group,text}));
}
const shiftCatalog={kinds:{}};
for(const title of ['오픈 순서','마감 순서']){const entry=kb.find(e=>e.file==='09_운영_매뉴얼'&&e.title===title);if(!entry)throw new Error('Missing checklist: '+title);shiftCatalog.kinds[title]=checklistTasks(entry.body);}
const checklistHash=crypto.createHash('sha256').update(JSON.stringify(shiftCatalog.kinds)).digest('hex').slice(0,10);
shiftCatalog.version=checklistHash;
fs.writeFileSync(path.join(root,'서버','shifts-catalog.js'),'// Generated by 도구/빌드.js\nexport default '+safe(shiftCatalog)+';\n');

const built=tpl.replace('/*KB_JSON*/[]',safe(kb)).replace('/*WINE_JSON*/[]',safe(wines)).replace('/*FOOD_JSON*/[]',safe(foods)).replace('/*WINE_MENU_JSON*/[]',safe(wineMenu)).replace('/*VERSION_JSON*/{}',safe({sourceHash,checklistHash})).replace('/*AI_ENDPOINT_JSON*/""',safe(endpoint)).replace('/*QUESTION_LOG_ENABLED*/false',safe(logEnabled));
fs.writeFileSync(path.join(root,'챗봇_시안.html'),built);
console.log('항목',kb.length,'개 내장');

